# Generated by Django 3.2.6 on 2021-09-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('amount', models.IntegerField(primary_key=True, serialize=False)),
                ('stripe_price_id', models.CharField(max_length=100)),
            ],
        ),
    ]
