# Generated by Django 3.2.6 on 2021-09-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
