# Generated by Django 3.2.6 on 2021-09-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aless_art_shop', '0003_product_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
