# Generated by Django 3.1 on 2021-08-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aless_art_shop', '0004_auto_20210824_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='listing',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='aless_art_shop.listing'),
        ),
    ]
