# Generated by Django 3.2.6 on 2021-09-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aless_art_shop', '0004_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('amount', models.IntegerField(primary_key=True, serialize=False)),
                ('stripe_price_id', models.CharField(max_length=100)),
            ],
        ),
    ]
