# Generated by Django 3.1 on 2021-08-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aless_art_shop', '0005_auto_20210824_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Catalogue',
        ),
    ]
