# Generated by Django 3.2.6 on 2021-10-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aless_art_shop', '0006_auto_20210915_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
