# Generated by Django 3.1 on 2021-08-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aless_art_shop', '0006_auto_20210824_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='listing',
            new_name='product',
        ),
    ]
