# Generated by Django 3.2.6 on 2021-10-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aless_art_shop', '0007_product_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
