# Generated by Django 3.2.6 on 2021-10-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aless_art_shop', '0009_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
