# Generated by Django 3.2.6 on 2021-10-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aless_art_shop', '0010_blogpost_blog_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='sub_heading',
            field=models.CharField(default='sub-heading', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
