# Generated by Django 3.2.6 on 2021-10-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aless_art_shop', '0011_blogpost_sub_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
