# Generated by Django 3.2.6 on 2021-10-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aless_art_shop', '0012_blogpost_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('BlogPost', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aless_art_shop.blogpost')),
            ],
        ),
    ]
