# Generated by Django 3.2.6 on 2021-10-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aless_art_shop', '0013_blogimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogimage',
            old_name='BlogPost',
            new_name='postname',
        ),
    ]
