# Generated by Django 3.2.6 on 2021-10-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aless_art_shop', '0016_alter_blogimage_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video_embed_url',
            field=models.TextField(blank=True),
        ),
    ]
